"""init tables netsync gov

Revision ID: 0530d82fa23e
Revises: 
Create Date: 2026-04-19 23:04:22.497310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0530d82fa23e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('entreprise', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('email_verifie', sa.Boolean(), nullable=True),
    sa.Column('token_verification', sa.String(length=255), nullable=True),
    sa.Column('date_expiration_plan', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonnes_email'), 'abonnes', ['email'], unique=True)
    op.create_table('appels_offres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('autorite_contractante', sa.String(length=255), nullable=True),
    sa.Column('secteur', sa.String(length=100), nullable=True),
    sa.Column('type_procedure', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('montant_estime', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('est_urgent', sa.Boolean(), nullable=True),
    sa.Column('jours_restants', sa.Integer(), nullable=True),
    sa.Column('numero_quotidien', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('contact_nom', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('dao_disponible', sa.Boolean(), nullable=True),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appels_offres_autorite_contractante'), 'appels_offres', ['autorite_contractante'], unique=False)
    op.create_index(op.f('ix_appels_offres_date_cloture'), 'appels_offres', ['date_cloture'], unique=False)
    op.create_index(op.f('ix_appels_offres_date_publication'), 'appels_offres', ['date_publication'], unique=False)
    op.create_index(op.f('ix_appels_offres_reference'), 'appels_offres', ['reference'], unique=False)
    op.create_index(op.f('ix_appels_offres_secteur'), 'appels_offres', ['secteur'], unique=False)
    op.create_index(op.f('ix_appels_offres_statut'), 'appels_offres', ['statut'], unique=False)
    op.create_table('pipeline_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_quotidien', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('nb_ao_extraits', sa.Integer(), nullable=True),
    sa.Column('nb_ao_nouveaux', sa.Integer(), nullable=True),
    sa.Column('nb_alertes', sa.Integer(), nullable=True),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('duree_secondes', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envois_alertes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abonne_id', sa.UUID(), nullable=True),
    sa.Column('ao_id', sa.UUID(), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['abonne_id'], ['abonnes.id'], ),
    sa.ForeignKeyConstraint(['ao_id'], ['appels_offres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['abonnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoris',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abonne_id', sa.UUID(), nullable=True),
    sa.Column('ao_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['abonne_id'], ['abonnes.id'], ),
    sa.ForeignKeyConstraint(['ao_id'], ['appels_offres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abonne_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('montant', sa.Integer(), nullable=True),
    sa.Column('devise', sa.String(length=10), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('plan_achete', sa.String(length=20), nullable=True),
    sa.Column('operateur', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['abonne_id'], ['abonnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_transaction_id'), 'paiements', ['transaction_id'], unique=True)
    op.create_table('preferences_alertes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('abonne_id', sa.UUID(), nullable=True),
    sa.Column('secteurs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mots_cles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('canal_email', sa.Boolean(), nullable=True),
    sa.Column('canal_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('heure_alerte', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['abonne_id'], ['abonnes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abonne_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences_alertes')
    op.drop_index(op.f('ix_paiements_transaction_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_table('favoris')
    op.drop_table('equipes')
    op.drop_table('envois_alertes')
    op.drop_table('pipeline_logs')
    op.drop_index(op.f('ix_appels_offres_statut'), table_name='appels_offres')
    op.drop_index(op.f('ix_appels_offres_secteur'), table_name='appels_offres')
    op.drop_index(op.f('ix_appels_offres_reference'), table_name='appels_offres')
    op.drop_index(op.f('ix_appels_offres_date_publication'), table_name='appels_offres')
    op.drop_index(op.f('ix_appels_offres_date_cloture'), table_name='appels_offres')
    op.drop_index(op.f('ix_appels_offres_autorite_contractante'), table_name='appels_offres')
    op.drop_table('appels_offres')
    op.drop_index(op.f('ix_abonnes_email'), table_name='abonnes')
    op.drop_table('abonnes')
    # ### end Alembic commands ###
