"""add plan_expire_le and ao_consultes_auj to abonne

Revision ID: b1d75edbe8fa
Revises: 0530d82fa23e
Create Date: 2026-04-20 01:20:05.486403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d75edbe8fa'
down_revision: Union[str, Sequence[str], None] = '0530d82fa23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonnes', sa.Column('plan_expire_le', sa.Date(), nullable=True))
    op.add_column('abonnes', sa.Column('ao_consultes_auj', sa.Integer(), nullable=True))
    op.add_column('abonnes', sa.Column('ao_consultes_reset_le', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abonnes', 'ao_consultes_reset_le')
    op.drop_column('abonnes', 'ao_consultes_auj')
    op.drop_column('abonnes', 'plan_expire_le')
    # ### end Alembic commands ###
