"""add trial and subscription management columns

Revision ID: cdec5abcd479
Revises: eb0aa4fff9b4
Create Date: 2026-04-23 12:58:15.018040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdec5abcd479'
down_revision: Union[str, Sequence[str], None] = 'eb0aa4fff9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonnes', sa.Column('trial_actif', sa.Boolean(), nullable=True))
    op.add_column('abonnes', sa.Column('trial_expire_le', sa.Date(), nullable=True))
    op.add_column('abonnes', sa.Column('plan_periode', sa.String(length=20), nullable=True))
    op.add_column('abonnes', sa.Column('derniere_facture_id', sa.String(length=100), nullable=True))
    op.add_column('abonnes', sa.Column('nb_renouvellements', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abonnes', 'nb_renouvellements')
    op.drop_column('abonnes', 'derniere_facture_id')
    op.drop_column('abonnes', 'plan_periode')
    op.drop_column('abonnes', 'trial_expire_le')
    op.drop_column('abonnes', 'trial_actif')
    # ### end Alembic commands ###
