"""add totp 2fa columns to abonne

Revision ID: eb0aa4fff9b4
Revises: b1d75edbe8fa
Create Date: 2026-04-22 13:58:27.871388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0aa4fff9b4'
down_revision: Union[str, Sequence[str], None] = 'b1d75edbe8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonnes', sa.Column('totp_secret', sa.String(length=32), nullable=True))
    op.add_column('abonnes', sa.Column('totp_active', sa.Boolean(), nullable=True))
    op.add_column('abonnes', sa.Column('totp_backup_codes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abonnes', 'totp_backup_codes')
    op.drop_column('abonnes', 'totp_active')
    op.drop_column('abonnes', 'totp_secret')
    # ### end Alembic commands ###
